train:
  # Run name for the training session.
  run_name: parking_detector
  # Directory in which model checkpoints & summaries (for Tensorboard) will be saved.
  job_dir: ../jobs/

  # Number of epochs (complete dataset batches) to run.
  num_epochs: 500

#  learning_rate:
#    decay_method: piecewise_constant
#    boundaries: [250000, 450000, 600000]
#    values: [0.0003, 0.0001, 0.00003, 0.00001]

dataset:
  type: object_detection
  # From which directory to read the dataset. dataset refers to tfrecord files
  dir: ../out/

model:
  type: fasterrcnn
#  type: ssd
  network:
    # Total number of classes to predict.
    num_classes: 2


  
